<ActionMenuLayout>:
    rows: 4
    cols: 3

    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
    Button:
        text: 'b1'
